---
author: Pranav
execute: 
    freeze: true
format: 
    revealjs:
        theme: [serif,custom.scss]
        slide-number: true
        css: custom.css
        transition: slide
        transition-speed: default
        chalkboard: true
        margin: 0.1
---

## Cosserat Rod Theory {.smaller}

**Conservation of Linear Momentum:** 

$$
\small{\rho A \cdot \partial_t^2 \bar{\mathbf{r}} = \overbrace{\partial_s \left( \frac{\mathbf{Q}^T \mathbf{S} \boldsymbol{\sigma}}{e} \right)}^{\substack{\text{internal shear/} \\ \text{stretch force}}} + \overbrace{e \ \bar{\mathbf{f}}}^{\substack{\text{external} \\ \text{force}}} }
$$

**Conservation of Angular Momentum:** 

$$
\small{\begin{align}\frac{\rho \mathbf{I}}{e} \cdot \partial_t \boldsymbol{\omega}&=\overbrace{\partial_s \left( \frac{\mathbf{B} \boldsymbol{\kappa}}{e^3} \right) + \frac{\boldsymbol{\kappa} \times \mathbf{B} \boldsymbol{\kappa}}{e^3}}^{\text{internal bend/twist couple}}+\overbrace{\left( \mathbf{Q}\frac{\bar{\mathbf{r}}_s}{e} \times \mathbf{S} \boldsymbol{\sigma} \right)}^{\substack{\text{internal shear/} \\ \text{stretch couple}}}+\overbrace{\left( \rho \mathbf{I} \cdot \frac{\boldsymbol{\omega}}{e} \right) \times \boldsymbol{\omega}}^{\text{Lagrangian transport}}+\overbrace{\frac{\rho \mathbf{I} \boldsymbol{\omega}}{e^2} \cdot \partial_t e}^{\text{unsteady dilation}}+\overbrace{e \ \mathbf{c}}^{\substack{\text{external} \\ \text{couple}}}
\end{align}}
$$

By solving these equations with suitable boundary conditions, we can model the dynamics of a single Cosserat elastic rod.

::: aside
M. Tummers, et. al., "Cosserat Rod Modeling of Continuum Robots from Newtonian and Lagrangian Perspectives," in IEEE Transactions on Robotics, vol. 39, no. 3, pp. 2360-2378, June 2023, doi: 10.1109/TRO.2023.3238171.
:::

## Properties

Density = 1.230 g/cm^3^ (Assuming as Natural Rubber)

Young's Modulus = 3.605 MPa

Shear Modulus = 1.209 MPa

Poisson's Ratio = 0.49

Radius = 2.43 mm (Assuming Equivalent Mass)

No. of Elements = 100

## Position 1 - Case 1 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p1c1 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p1c1e >}}
:::
::::

## Position 1 - Case 2 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p1c2 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p1c2e >}}
:::
::::

## Position 1 - Case 3 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p1c3 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p1c3e >}}
:::
::::

## Position 2 - Case 1 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p2c1 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p2c1e >}}
:::
::::

## Position 2 - Case 2 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p2c2 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p2c2e >}}
:::
::::

## Position 2 - Case 3 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p2c3 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p2c3e >}}
:::
::::

## Position 3 - Case 1 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p3c1 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p3c1e >}}
:::
::::

## Position 3 - Case 2 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p3c2 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p3c2e >}}
:::
::::

## Position 3 - Case 3 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p3c3 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p3c3e >}}
:::
::::

## Position 4 - Case 1 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p4c1 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p4c1e >}}
:::
::::

## Position 4 - Case 2 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p4c2 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p4c2e >}}
:::
::::

## Position 4 - Case 3 {.r-stretch}
:::: {.columns}
::: {.column width="58%"}
{{< embed plotter.ipynb#p4c3 >}}
:::
::: {.column width="42%"}
{{< embed plotter.ipynb#p4c3e >}}
:::
:::: 

## Error Metrics {.smaller style="text-align: center; font-size: 75%;"}


<table class="dataframe">
  <thead>
    <tr style="font-size: 85%;">
      <th></th>
      <th>Position</th>
      <th>Case</th>
      <th>Length - Prototype</th>
      <th>MD Error - Hermite</th>
      <th>MD Error - Simulation</th>
      <th>Length Error - Hermite</th>
      <th>Length Error - Simulation</th>
    </tr>
  </thead>
  <tbody>
    <tr style="font-size: 75%;">
      <th>0</th>
      <td>1</td>
      <td>1</td>
      <td>192.160</td>
      <td>22.695</td>
      <td>10.759</td>
      <td>0.0</td>
      <td>-0.007</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>1</th>
      <td>1</td>
      <td>2</td>
      <td>183.671</td>
      <td>29.268</td>
      <td>10.025</td>
      <td>0.0</td>
      <td>-0.011</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>2</th>
      <td>1</td>
      <td>3</td>
      <td>217.601</td>
      <td>22.226</td>
      <td>15.326</td>
      <td>0.0</td>
      <td>-0.018</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>3</th>
      <td>2</td>
      <td>1</td>
      <td>192.181</td>
      <td>29.337</td>
      <td>7.328</td>
      <td>0.0</td>
      <td>-0.020</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>4</th>
      <td>2</td>
      <td>2</td>
      <td>183.667</td>
      <td>21.194</td>
      <td>17.542</td>
      <td>0.0</td>
      <td>-0.016</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>5</th>
      <td>2</td>
      <td>3</td>
      <td>217.588</td>
      <td>20.111</td>
      <td>22.851</td>
      <td>0.0</td>
      <td>-0.036</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>6</th>
      <td>3</td>
      <td>1</td>
      <td>192.184</td>
      <td>32.330</td>
      <td>9.157</td>
      <td>0.0</td>
      <td>-0.043</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>7</th>
      <td>3</td>
      <td>2</td>
      <td>183.680</td>
      <td>19.543</td>
      <td>19.364</td>
      <td>0.0</td>
      <td>-0.022</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>8</th>
      <td>3</td>
      <td>3</td>
      <td>217.567</td>
      <td>26.515</td>
      <td>20.495</td>
      <td>0.0</td>
      <td>-0.050</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>9</th>
      <td>4</td>
      <td>1</td>
      <td>192.240</td>
      <td>20.925</td>
      <td>7.946</td>
      <td>0.0</td>
      <td>-0.065</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>10</th>
      <td>4</td>
      <td>2</td>
      <td>184.719</td>
      <td>19.015</td>
      <td>21.117</td>
      <td>0.0</td>
      <td>-0.030</td>
    </tr>
    <tr style="font-size: 75%;">
      <th>11</th>
      <td>4</td>
      <td>3</td>
      <td>217.558</td>
      <td>28.402</td>
      <td>21.767</td>
      <td>0.0</td>
      <td>-0.064</td>
    </tr>
  </tbody>
</table>

::: {style="font-size: 70%; text-align: right;"}
***^Units: mm***
:::