---
author: Pranav
format: 
    revealjs:
        theme: [serif,custom.scss]
        slide-number: true
        css: custom.css
        transition: slide
        transition-speed: default
        chalkboard: true
        margin: 0.1
---

## Arc Length Constrained Hermite {.smaller}

</br>

Min. $f(x)$ = $L($ Hermite ( p~0~ , p~1~ , x\* u~0~ , x\* u~1~ )  $)$ – $L($ Prototype $)$

</br>

*where,*

$L( )$ : Length function

p~0~ &nbsp;&nbsp;&nbsp;: Starting point

p~1~ &nbsp;&nbsp;&nbsp;: Ending point

u~0~ &nbsp;&nbsp;&nbsp;: Unit Tangent at p0

u~1~ &nbsp;&nbsp;&nbsp;: Unit Tangent at p1

x &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Magnitude for u~0~ & u~1~ (Optimization Variable)

## Position 1 - Case 1 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p1-case1.html"></iframe>
```

## Position 1 - Case 2 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p1-case2.html"></iframe>
```

## Position 1 - Case 3 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p1-case3.html"></iframe>
```


## Position 2 - Case 1 {.r-stretch} 

```{=html}
<iframe width="100%" height="100%" src="p2-case1.html"></iframe>
```

## Position 2 - Case 2 {.r-stretch} 

```{=html}
<iframe width="100%" height="100%" src="p2-case2.html"></iframe>
```

## Position 2 - Case 3 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p2-case3.html"></iframe>
```

## Position 3 - Case 1 {.r-stretch} 

```{=html}
<iframe width="100%" height="100%" src="p3-case1.html"></iframe>
```

## Position 3 - Case 2 {.r-stretch} 

```{=html}
<iframe width="100%" height="100%" src="p3-case2.html"></iframe>
```

## Position 3 - Case 3 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p3-case3.html"></iframe>
```

## Position 4 - Case 1 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p4-case1.html"></iframe>
```

## Position 4 - Case 2 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p4-case2.html"></iframe>
```

## Position 4 - Case 3 {.r-stretch}

```{=html}
<iframe width="100%" height="100%" src="p4-case3.html"></iframe>
```

## Error Metrics {.smaller style="text-align: center; font-size: 75%;"}

<div>
<table class="dataframe">
  <thead>
    <tr style="font-size: 85%;">
      <th>Position</th>
      <th>Case</th>
      <th>Computed Magnitude</th>
      <th>Length - Prototype</th>
      <th>Length - Optimized Hermite</th>
      <th>Error - Midpoint Deviation</th>
      <th>Error - Length</th>
    </tr>
  </thead>
  <tbody>
    <tr style="font-size: 75%;">
      <td>1</td>
      <td>1</td>
      <td>339.231</td>
      <td>192.160</td>
      <td>192.160</td>
      <td>27.232</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>1</td>
      <td>2</td>
      <td>428.425</td>
      <td>183.671</td>
      <td>183.671</td>
      <td>29.464</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>1</td>
      <td>3</td>
      <td>410.361</td>
      <td>217.601</td>
      <td>217.601</td>
      <td>24.393</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>2</td>
      <td>1</td>
      <td>326.361</td>
      <td>192.181</td>
      <td>192.181</td>
      <td>31.582</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>2</td>
      <td>2</td>
      <td>375.337</td>
      <td>183.667</td>
      <td>183.667</td>
      <td>22.649</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>2</td>
      <td>3</td>
      <td>430.615</td>
      <td>217.588</td>
      <td>217.588</td>
      <td>31.889</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>3</td>
      <td>1</td>
      <td>329.663</td>
      <td>192.184</td>
      <td>192.184</td>
      <td>37.735</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>3</td>
      <td>2</td>
      <td>346.258</td>
      <td>183.675</td>
      <td>183.675</td>
      <td>21.762</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>3</td>
      <td>3</td>
      <td>444.335</td>
      <td>217.567</td>
      <td>217.567</td>
      <td>44.350</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>4</td>
      <td>1</td>
      <td>349.239</td>
      <td>192.240</td>
      <td>192.240</td>
      <td>40.860</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>4</td>
      <td>2</td>
      <td>331.333</td>
      <td>184.719</td>
      <td>184.719</td>
      <td>24.860</td>
      <td>0.0</td>
    </tr>
    <tr style="font-size: 75%;">
      <td>4</td>
      <td>3</td>
      <td>458.466</td>
      <td>217.558</td>
      <td>217.558</td>
      <td>49.024</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
</div>